# Generated by Django 6.0.5 on 2026-05-15 00:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код языка')),
                ('name', models.CharField(max_length=100, verbose_name='Название языка')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название урока')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок урока')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.language', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['language', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CompletedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percent', models.IntegerField(verbose_name='Результат (%)')),
                ('correct_count', models.IntegerField(verbose_name='Правильных ответов')),
                ('total_count', models.IntegerField(verbose_name='Всего слов')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прохождения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tests', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tests', to='core.lesson')),
            ],
            options={
                'verbose_name': 'Пройденный тест',
                'verbose_name_plural': 'Пройденные тесты',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255, verbose_name='Иностранное слово')),
                ('translation', models.CharField(max_length=255, verbose_name='Перевод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('categories', models.ManyToManyField(blank=True, related_name='words', to='core.category', verbose_name='Категории')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='core.language', verbose_name='Язык')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='core.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
                'ordering': ['lesson__order', 'term'],
            },
        ),
        migrations.CreateModel(
            name='WordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastered', models.BooleanField(default=False, verbose_name='Слово изучено')),
                ('correct_count', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='Неправильных ответов')),
                ('last_answered', models.DateTimeField(blank=True, null=True, verbose_name='Последний ответ')),
                ('next_review_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующее повторение')),
                ('review_interval_days', models.IntegerField(default=1, verbose_name='Интервал повторения (дней)')),
                ('review_stage', models.IntegerField(default=0, verbose_name='Стадия повторения (0-5)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_progress', to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.word')),
            ],
            options={
                'verbose_name': 'Прогресс слова',
                'verbose_name_plural': 'Прогресс слов',
                'unique_together': {('user', 'word')},
            },
        ),
    ]
