# Generated by Django 6.0.5 on 2026-05-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_word_options_lesson_word_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='direction',
            field=models.CharField(choices=[('foreign_to_native', 'Иностранное → Перевод (показываем иностранное)'), ('native_to_foreign', 'Перевод → Иностранное (показываем перевод)')], default='foreign_to_native', max_length=20, verbose_name='Направление обучения'),
        ),
        migrations.AlterField(
            model_name='word',
            name='term',
            field=models.CharField(max_length=255, verbose_name='Иностранное слово'),
        ),
    ]
