# Generated by Django 6.0.5 on 2026-05-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_word_direction_alter_word_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='direction',
        ),
    ]
